spring:
  application:
    name: @name@
    description: @description@
---
info:
  version: @version@
  responsible: Anatoly Cherkasov
  stage: dev
---
management:
  metrics:
    export:
      statsd:
        flavor: etsy
---
server:
  port: @server.port@
---
adapter:
  callbackUrl: http://127.0.0.1:8018
  pathAcsUrl: "/mpi/acs"
---
fixture:
  cards: classpath:fixture/cards.csv
